/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven { url = uri("https://repo.maven.apache.org/maven2/") }
}

dependencies {
    testImplementation(libs.junit.junit)
    compileOnly(libs.com.google.android.android)
}

sourceSets {
    main {
        java {
            srcDirs("src")
        }
    }
}

group = "net.jthink"

version = "2.3.15"

description = "jaudiotagger"

java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing { publications.create<MavenPublication>("maven") { from(components["java"]) } }

tasks.withType<JavaCompile>() { options.encoding = "UTF-8" }

tasks.withType<Javadoc>() { options.encoding = "UTF-8" }
